name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: "0 3 * * 0" # every Sunday at 3am

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  CI: true
  TURBO_API: http://127.0.0.1:9080
  TURBO_TOKEN: this-is-not-a-secret
  TURBO_TEAM: myself

jobs:
  install_dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: felixmosh/turborepo-gh-artifacts@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: NullVoxPopuli/action-setup-pnpm@v2.3.1

  lint:
    name: Lint Source
    runs-on: ubuntu-latest
    needs: [install_dependencies]
    steps:
      - uses: actions/checkout@v5
      - uses: felixmosh/turborepo-gh-artifacts@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: NullVoxPopuli/action-setup-pnpm@v2.3.1
      - run: pnpm lint

  esm_tests:
    name: ESM Tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    needs: [install_dependencies]
    strategy:
      matrix:
        node:
          - "14"
          - "16"
          - "18"
          - "20"
    steps:
      - uses: actions/checkout@v5
      - uses: felixmosh/turborepo-gh-artifacts@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: NullVoxPopuli/action-setup-pnpm@v2.3.1
      - name: Test Modules with ${{ matrix.node }}
        run: pnpm test
        working-directory: tests-esm

  cjs_tests:
    name: CJS Tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    needs: [install_dependencies]
    strategy:
      matrix:
        node:
          - "14"
          - "16"
          - "18"
          - "20"
    steps:
      - uses: actions/checkout@v5
      - uses: felixmosh/turborepo-gh-artifacts@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: NullVoxPopuli/action-setup-pnpm@v2.3.1
      - name: Test CJS with ${{ matrix.node }}
        run: pnpm test
        working-directory: tests-cjs


  hljs_tests:
    name: "Highlight.js Tests"
    timeout-minutes: 5
    runs-on: ubuntu-latest
    needs: [install_dependencies]
    steps:
      - uses: actions/checkout@v5
      - uses: felixmosh/turborepo-gh-artifacts@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: NullVoxPopuli/action-setup-pnpm@v2.3.1
      - run: scripts/hljs-test.sh
        working-directory: highlightjs-glimmer

